services:
  db:
    container_name: lunchlog_db
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust #  This shouldn't be like that for production purposes
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  app:
    build: .
    container_name: lunchlog_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python lunchlog/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/lunchlog

volumes:
  postgres_data:
