# Generated by Django 5.0.6 on 2024-07-01 11:50

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lunch", "0002_receipt_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="file",
            field=models.FileField(
                default=None,
                storage=config.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
            preserve_default=False,
        ),
    ]
