# Generated by Django 5.0.6 on 2024-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lunch", "0008_restaurant_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="delivery",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_beer",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_breakfast",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_brunch",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_dinner",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_lunch",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_vegetarian_food",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_wine",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="takeout",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
