# Generated by Django 5.0.6 on 2024-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lunch", "0009_alter_restaurant_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="place_id",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
