# Generated by Django 5.0.6 on 2024-07-08 08:16

import lunch.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lunch", "0012_restaurant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="image",
            field=models.ImageField(upload_to=lunch.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="delivery",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="place_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_beer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_breakfast",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_brunch",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_dinner",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_lunch",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_vegetarian_food",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="serves_wine",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="takeout",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
