# Generated by Django 5.0.6 on 2024-07-02 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("3be15075-3dce-43bb-97ec-7cbea3fdd40b"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
