# Generated by Django 5.0.6 on 2024-07-02 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("52c4926d-85f8-4543-8263-422499ab1bc3"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
