# Generated by Django 5.0.6 on 2024-07-02 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("cbf02ff7-da0c-4508-88f7-78843863ce60"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
