# Generated by Django 5.0.6 on 2024-07-02 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("8d3fd29b-226d-4231-8eae-7f4eb3db9986"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
