# Generated by Django 5.0.6 on 2024-07-04 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("011bec54-ddcb-4cc2-8465-6d01392d3537"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
