# Generated by Django 5.0.6 on 2024-07-04 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("39bf645b-abbb-4d95-9c92-d9c48821714d"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
