# Generated by Django 5.0.6 on 2024-07-04 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("aae45075-ad1a-4877-8fcb-961a8db7b76d"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
