# Generated by Django 5.0.6 on 2024-07-04 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0596d2d8-3d11-4d61-8e67-5afb24080bc8"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
