# Generated by Django 5.0.6 on 2024-07-04 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("050fa09e-5c97-4a8e-883e-cd8db1c410fe"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
