# Generated by Django 5.0.6 on 2024-07-04 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_customuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("5da8c7eb-1b6e-4c62-a3a4-4899e0e2fdcc"),
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
